/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_newtek_ndidemo_MainActivity */

#ifndef _Included_com_newtek_ndidemo_MainActivity
#define _Included_com_newtek_ndidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_newtek_ndidemo_MainActivity
 * Method:    testNDIInitialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_newtek_ndidemo_MainActivity_testNDIInitialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
